import { colors } from "@/constants/colors";
import { Category, MovementKind } from "@/types/finance.types";

export const incomeCategories: Category[] = [
  {
    id: "salary",
    name: "Sueldo",
    labelI18nKey: "categories.salary",
    type: "income",
    icon: "briefcase",
    color: colors.dark.income,
  },
  {
    id: "freelance",
    name: "Proyecto / Freelance",
    labelI18nKey: "categories.freelance",
    type: "income",
    icon: "laptop",
    color: colors.dark.secondary,
  },
  {
    id: "sales",
    name: "Ventas",
    labelI18nKey: "categories.sales",
    type: "income",
    icon: "shopping-bag",
    color: colors.dark.income,
  },
  {
    id: "business_income",
    name: "Negocio",
    labelI18nKey: "categories.business_income",
    type: "income",
    icon: "store",
    color: colors.dark.primary,
  },
  {
    id: "investment_income",
    name: "Inversión",
    labelI18nKey: "categories.investment_income",
    type: "income",
    icon: "trending-up",
    color: colors.dark.primary,
  },
  {
    id: "gift_income",
    name: "Regalo / Extra",
    labelI18nKey: "categories.gift_income",
    type: "income",
    icon: "gift",
    color: colors.dark.warning,
  },
  {
    id: "refund",
    name: "Reembolso",
    labelI18nKey: "categories.refund",
    type: "income",
    icon: "rotate-ccw",
    color: colors.dark.secondary,
  },
  {
    id: "loan_received",
    name: "Préstamo recibido",
    labelI18nKey: "categories.loan_received",
    type: "income",
    icon: "hand-coins",
    color: colors.dark.warning,
  },
  {
    id: "rental_income",
    name: "Alquiler recibido",
    labelI18nKey: "categories.rental_income",
    type: "income",
    icon: "home",
    color: colors.dark.income,
  },
  {
    id: "other_income",
    name: "Otros ingresos",
    labelI18nKey: "categories.other_income",
    type: "income",
    icon: "circle-dollar-sign",
    color: colors.dark.textMuted,
  },
];

export const expenseCategories: Category[] = [
  {
    id: "food",
    name: "Alimentación",
    labelI18nKey: "categories.food",
    type: "expense",
    icon: "utensils",
    color: colors.dark.expense,
  },
  {
    id: "groceries",
    name: "Supermercado",
    labelI18nKey: "categories.groceries",
    type: "expense",
    icon: "shopping-cart",
    color: colors.dark.expense,
  },
  {
    id: "restaurants",
    name: "Restaurantes",
    labelI18nKey: "categories.restaurants",
    type: "expense",
    icon: "chef-hat",
    color: colors.dark.warning,
  },
  {
    id: "transport",
    name: "Transporte",
    labelI18nKey: "categories.transport",
    type: "expense",
    icon: "car",
    color: colors.dark.secondary,
  },
  {
    id: "fuel",
    name: "Combustible",
    labelI18nKey: "categories.fuel",
    type: "expense",
    icon: "fuel",
    color: colors.dark.warning,
  },
  {
    id: "taxi_rideshare",
    name: "Taxi / Apps",
    labelI18nKey: "categories.taxi_rideshare",
    type: "expense",
    icon: "car-taxi-front",
    color: colors.dark.secondary,
  },
  {
    id: "housing",
    name: "Vivienda",
    labelI18nKey: "categories.housing",
    type: "expense",
    icon: "home",
    color: colors.dark.primary,
  },
  {
    id: "rent",
    name: "Arriendo",
    labelI18nKey: "categories.rent",
    type: "expense",
    icon: "key-round",
    color: colors.dark.primary,
  },
  {
    id: "services",
    name: "Servicios",
    labelI18nKey: "categories.services",
    type: "expense",
    icon: "receipt",
    color: colors.dark.warning,
  },
  {
    id: "electricity",
    name: "Electricidad",
    labelI18nKey: "categories.electricity",
    type: "expense",
    icon: "zap",
    color: colors.dark.warning,
  },
  {
    id: "water",
    name: "Agua",
    labelI18nKey: "categories.water",
    type: "expense",
    icon: "droplets",
    color: colors.dark.secondary,
  },
  {
    id: "internet_phone",
    name: "Internet / Teléfono",
    labelI18nKey: "categories.internet_phone",
    type: "expense",
    icon: "wifi",
    color: colors.dark.primary,
  },
  {
    id: "health",
    name: "Salud",
    labelI18nKey: "categories.health",
    type: "expense",
    icon: "heart-pulse",
    color: colors.dark.expense,
  },
  {
    id: "medicine",
    name: "Medicina",
    labelI18nKey: "categories.medicine",
    type: "expense",
    icon: "pill",
    color: colors.dark.expense,
  },
  {
    id: "education",
    name: "Educación",
    labelI18nKey: "categories.education",
    type: "expense",
    icon: "graduation-cap",
    color: colors.dark.secondary,
  },
  {
    id: "entertainment",
    name: "Entretenimiento",
    labelI18nKey: "categories.entertainment",
    type: "expense",
    icon: "gamepad-2",
    color: colors.dark.primary,
  },
  {
    id: "subscriptions",
    name: "Suscripciones",
    labelI18nKey: "categories.subscriptions",
    type: "expense",
    icon: "repeat",
    color: colors.dark.warning,
  },
  {
    id: "technology",
    name: "Tecnología",
    labelI18nKey: "categories.technology",
    type: "expense",
    icon: "smartphone",
    color: colors.dark.secondary,
  },
  {
    id: "clothing",
    name: "Ropa",
    labelI18nKey: "categories.clothing",
    type: "expense",
    icon: "shirt",
    color: colors.dark.primary,
  },
  {
    id: "personal_care",
    name: "Cuidado personal",
    labelI18nKey: "categories.personal_care",
    type: "expense",
    icon: "sparkles",
    color: colors.dark.secondary,
  },
  {
    id: "family",
    name: "Familia",
    labelI18nKey: "categories.family",
    type: "expense",
    icon: "users",
    color: colors.dark.warning,
  },
  {
    id: "pets",
    name: "Mascotas",
    labelI18nKey: "categories.pets",
    type: "expense",
    icon: "paw-print",
    color: colors.dark.secondary,
  },
  {
    id: "travel",
    name: "Viajes",
    labelI18nKey: "categories.travel",
    type: "expense",
    icon: "plane",
    color: colors.dark.primary,
  },
  {
    id: "gifts",
    name: "Regalos",
    labelI18nKey: "categories.gifts",
    type: "expense",
    icon: "gift",
    color: colors.dark.warning,
  },
  {
    id: "taxes",
    name: "Impuestos",
    labelI18nKey: "categories.taxes",
    type: "expense",
    icon: "landmark",
    color: colors.dark.expense,
  },
  {
    id: "fees",
    name: "Comisiones",
    labelI18nKey: "categories.fees",
    type: "expense",
    icon: "badge-dollar-sign",
    color: colors.dark.warning,
  },
  {
    id: "debt_payment",
    name: "Pago de deuda",
    labelI18nKey: "categories.debt_payment",
    type: "expense",
    icon: "credit-card",
    color: colors.dark.expense,
  },
  {
    id: "savings",
    name: "Ahorro",
    labelI18nKey: "categories.savings",
    type: "expense",
    icon: "piggy-bank",
    color: colors.dark.income,
  },
  {
    id: "investment_expense",
    name: "Inversión",
    labelI18nKey: "categories.investment_expense",
    type: "expense",
    icon: "trending-up",
    color: colors.dark.primary,
  },
  {
    id: "cash_withdrawal",
    name: "Retiro de efectivo",
    labelI18nKey: "categories.cash_withdrawal",
    type: "expense",
    icon: "banknote",
    color: colors.dark.secondary,
  },
];

export const sharedCategories: Category[] = [
  {
    id: "other",
    name: "Otros",
    labelI18nKey: "categories.other",
    type: "both",
    icon: "circle-dollar-sign",
    color: colors.dark.textMuted,
  },
];

export const categories: Category[] = [
  ...incomeCategories,
  ...expenseCategories,
  ...sharedCategories,
];

export function getCategoryById(categoryId: string) {
  return categories.find((category) => category.id === categoryId);
}

export function getCategoriesByMovementKind(kind: MovementKind): Category[] {
  return categories.filter(
    (category) => category.type === kind || category.type === "both",
  );
}

export function getCategoriesByType(kind: MovementKind): Category[] {
  return getCategoriesByMovementKind(kind);
}
